[build]
  publish = "/"

  # This handles your custom "Thank You" message after upload
  [[redirects]]
    from = "/tum-to-accha-admi-hee"
      to = "/index.html"
        status = 200

        # This is the safety net for Single Page Applications
        [[redirects]]
          from = "/*"
            to = "/index.html"
              status = 200
                force = false
                